logging:
  level:
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO

server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: producer-wikimedia-labs
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

wikimedia:
  stream:
    url: https://stream.wikimedia.org/v2/stream/recentchange