server:
  address: 0.0.0.0
  port: 8081

spring:
  application:
    name: producer-wikimedia-labs
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://schema-registry:8081}

wikimedia:
  stream:
    url: ${WIKIMEDIA_STREAM_URL}

app:
  kafka:
    topics:
      raw: ${APP_KAFKA_TOPICS_RAW}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO
    com.learn: DEBUG
    org.springframework.kafka: INFO
