server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: transform-wikimedia
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    consumer:
      group-id: wikimedia-processor
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
app:
  kafka:
    topics:
      raw: wikimedia.raw.events
      filtered: wikimedia.filtered.events
