server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: transform-wikimedia
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://schema-registry:8081}

app:
  kafka:
    topics:
      raw: ${APP_KAFKA_TOPICS_RAW}
      filtered: ${APP_KAFKA_TOPICS_FILTERED}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    com.learn: DEBUG
    org.springframework.kafka: INFO
