openapi: 3.0.3

info:
  title: Wikimedia Events Api
  description:
  contact:
    name: Andrés Reinaldo Cid
    email: andresrc345@gmail.com
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: Localhost

tags:
  - name: Wikimedia
    description: Operations about Wikimedia Events
paths:
  /v1/wikimedia-events:
    $ref: 'v1/services/wikimedia/wikimedia-events.yml'