openapi: 3.0.3

info:
  title: Wikimedia Analysis Api
  description: This API allows managing analysis of wikimedia event information within the system.
  contact:
    name: Andrés Reinaldo Cid
    email: andresrc345@gmail.com
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: Localhost

tags:
  - name: Analysis
    description: Operations about Wikimedia Analysis events
paths:
  /v1/analysis:
    $ref: 'v1/services/analysis/analysis.yml'

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT