server:
  address: 0.0.0.0
  port: 8090
  servlet:
    context-path: /api/wikimedia-events

spring:
  application:
    name: consumer-wikimedia
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      filtered: ${APP_KAFKA_TOPICS_FILTERED}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    com.learn: DEBUG
    org.springframework.kafka: INFO
