server:
  address: 0.0.0.0
  port: 8090
  servlet:
    context-path: /api/wikimedia-events

spring:
  application:
    name: template
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/wikimedia?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://schema-registry:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.KafkaAvroSerializer
    consumer:
      group-id: wikimedia-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.KafkaAvroSerializer
app:
  kafka:
    topics:
      filtered: wikimedia.filtered.events
      analyzed: wikimedia.analysis.events
  auth:
    secret:
      key: 51256bb1n23ad0d2cedeb37ed948763ccb366af17b219f0bd99c9754288975f7