server:
  address: 0.0.0.0
  port: 8090
  servlet:
    context-path: /api/wikimedia-events

spring:
  application:
    name: template
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/wikimedia?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8085
    consumer:
      group-id: wikimedia-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
app:
  kafka:
    topics:
      filtered: wikimedia.filtered.events
      analyzed: wikimedia.analysis.events
  auth:
    secret:
      key: 51256bb1n23ad0d2cedeb37ed948763ccb366af17b219f0bd99c9754288975f7